//! Utilities to adapt screen brightness to the ambient brightness measured by the VEML7700.
use anyhow::{Context, Result};
use tracing::instrument;
use zbus::{Connection, proxy};

/// Convert ambient brightness in lux to screen brightness as fraction (0.0 to 1.0).
pub fn ambient_to_screen_brightness(lux: f32) -> f32 {
    (lux / 50.0).clamp(0.0, 1.0) // TODO: Maybe use full brightness at 2000 lux instead of 50.
}

// # DBus interface proxy for: `rs.wl.gammarelay`
// Source: `Interface '/' from service 'rs.wl-gammarelay' on session bus`.
// This block was (mostly) generated by `zbus-xmlgen` `3.1.1` from DBus introspection data.
#[proxy(
    default_service = "rs.wl-gammarelay",
    interface = "rs.wl.gammarelay",
    default_path = "/"
)]
trait GammaRelay {
    /// ToggleInverted method
    fn toggle_inverted(&self) -> zbus::Result<()>;
    /// UpdateBrightness method
    fn update_brightness(&self, delta_brightness: f64) -> zbus::Result<()>;
    /// UpdateGamma method
    fn update_gamma(&self, delta_gamma: f64) -> zbus::Result<()>;
    /// UpdateTemperature method
    fn update_temperature(&self, delta_temp: i16) -> zbus::Result<()>;
    /// Brightness property
    #[zbus(property)]
    fn brightness(&self) -> zbus::Result<f64>;
    /// Gamma property
    #[zbus(property)]
    fn gamma(&self) -> zbus::Result<f64>;
    /// Inverted property
    #[zbus(property)]
    fn inverted(&self) -> zbus::Result<bool>;
    /// Temperature property
    #[zbus(property)]
    fn temperature(&self) -> zbus::Result<u16>;
}

#[instrument]
pub async fn apply_screen_brightness(brightness: f32) -> Result<()> {
    let connection = Connection::session()
        .await
        .context("Failed to create DBus connection")?;
    let proxy = GammaRelayProxy::new(&connection)
        .await
        .context("Failed to create GammaRelay proxy")?;
    let old_brightness = proxy.brightness()
        .await
        .context("Failed to get current brightness")?;
    let delta = brightness as f64 - old_brightness;
    let _ = proxy.update_brightness(delta)
        .await
        .context("Failed to update screen brightness")?;
    Ok(())
}
